### PR TITLE
Add go modules support

### LINKED ISSUE #51: incorrect release tags for go modules
Similar to #43 but did not want to try to revive a year old closed ticket. I also have some additional information on the problem and what I think is the solution.

Since `go.mod` is not at the root of the project, the required tag for the semver would be `statsd/v3.2.1`, whereas the current release tag is `v3.2.1`.

> Each module has its own version information. Version tags for modules below the root of the repository must include the relative directory as a prefix. [(source)](https://github.com/golang/go/wiki/Modules#what-are-multi-module-repositories)

**Additional Context**

This is the error when trying to use v3 with go modules, which is looking for the missing tag `statsd/v3.2.1`.
```
reading github.com/cactus/go-statsd-client/statsd/statsd/go.mod at revision statsd/v3.2.1: unknown revision statsd/v3.2.1
```

### PR DESCRIPTION
**Pull request by nrwiersma**
This adds support for go modules and updates the README to reflect these changes.

Fixes #51

### CODE REVIEW

**Comment by bzzoop** [comment]
Would this still work for folks who aren't using go mod currently, or who rely on the existing "+incompatible" format?
I would hate to suddenly break things for any existing users.

The go module system seems pretty clunky when coupled with a nested directory structure like this project uses (alas, this project was set up _long_ before go modules were a thing). I have a few times spent a chunk of time trying to get this to work properly for go.mod versioning while _also_ not breaking existing users, and did have much luck. I don't have a great deal of motivation to sink more of my free time into again. 

To be honest, folks are probably better off vendoring this library, or forking and adding go mod themselves to their fork, and just pulling any code updates from here into their fork (this would avoid breaking other folks relying on the current system).

**Comment by nrwiersma** [comment]
Go would see this as the latest version (with Go modules), so if you run `go get -u` it will switch to this version. If you have already got the old version in your mod, and you don't update it, it will not do anything.

If you wish to not break things for other users, I would switch this to v4, and once merged, tag it as v4.0.0. This would mean anyone using v3 will not see this change, as you would need to import `github.com/cactus/go-statsd-client/v4/statsd` for this to take effect. I can gladly make that change to my PR.

If you prefer to not change things, you can just close the PR.

The nested structure is handled fine by Go modules, it doesnt really care much about it, you just need to set the module version in the correct place. Having the `go.mod` deeper in the structure can work, but is difficult for people to figure everything out. Go actually has the ability to deal with nested versions under a `v2` or `v3` folder, or branched old versions, like a `v2` branch to maintain old versions. Once the `go.mod` is in place, the code no longer needs to be in the Go Path to work, as it uses the module path for reference.

**Comment by bzzoop** [comment]
@nrwiersma I think this looks ok. I did some testing and it seemed like it didn't cause any issues.
👍 
Thanks for the contribution and the great description.

I agree that pushing a v4 seems to make sense. If you could update your PR to a v4, I'll merge it then update the changelog and push a release.

<3

**Comment by bzzoop** [comment]
Actually, decided to just merge locally and make the change to v4 myself (no sense making you do it if I had to be in there poking around anyway).

Thanks again!

**Pull request merged**
